dist: bionic
language: d

d:
  - dmd

addons:
  apt:
    packages:
      - make

script:
  - dub fetch commandr
  - dub run commandr || true
  - make test

branches:
  only:
    - master

notifications:
  email:
    on_success: never
